package main

import (
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"

	errorsv1 "github.com/Servora-Kit/servora/api/gen/go/servora/errors/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	generatedSuffix           = "_errors.pb.go"
	generatorTargetGo         = "go"
	generatorTargetTypeScript = "ts"
)

var (
	fmtPackage    = protogen.GoImportPath("fmt")
	errorsPackage = protogen.GoImportPath("github.com/go-kratos/kratos/v3/errors")
)

type errorEntry struct {
	value    *protogen.EnumValue
	code     int32
	function string
	comment  string
}

type errorEnumModel struct {
	enum    *protogen.Enum
	values  []*protogen.EnumValue
	entries []errorEntry
}

type errorFileModel struct {
	enums        []errorEnumModel
	goEntryCount int
}

func generate(plugin *protogen.Plugin, target string) error {
	if target != generatorTargetGo && target != generatorTargetTypeScript {
		return fmt.Errorf(
			"unsupported generation target %q: want %q or %q",
			target,
			generatorTargetGo,
			generatorTargetTypeScript,
		)
	}

	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		model, err := analyzeErrorFile(file)
		if err != nil {
			return err
		}
		switch target {
		case generatorTargetGo:
			generateGoFile(plugin, file, model)
		case generatorTargetTypeScript:
			generateTypeScriptFile(plugin, file, model)
		}
	}
	return nil
}

func generateGoFile(plugin *protogen.Plugin, file *protogen.File, model errorFileModel) {
	if model.goEntryCount == 0 {
		return
	}

	generated := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+generatedSuffix, file.GoImportPath)
	generated.P("// Code generated by protoc-gen-go-errors. DO NOT EDIT.")
	generated.P()
	generated.P("package ", file.GoPackageName)
	generated.P()
	generated.P("// This is a compile-time assertion to ensure that this generated file")
	generated.P("// is compatible with the Kratos v3 errors package.")
	generated.P("const _ = ", errorsPackage.Ident("SupportPackageIsVersion1"))
	generated.P()

	for _, enum := range model.enums {
		for _, entry := range enum.entries {
			if entry.comment != "" {
				generated.P(entry.comment)
			}
			generated.P("func Is", entry.function, "(err error) bool {")
			generated.P("if err == nil {")
			generated.P("return false")
			generated.P("}")
			generated.P("e := ", errorsPackage.Ident("FromError"), "(err)")
			generated.P("return e.Reason == ", entry.value.GoIdent, ".String() && e.Code == ", entry.code)
			generated.P("}")
			generated.P()
			if entry.comment != "" {
				generated.P(entry.comment)
			}
			generated.P("func Error", entry.function, "(format string, args ...any) *", errorsPackage.Ident("Error"), " {")
			generated.P(
				"return ", errorsPackage.Ident("New"), "(", entry.code, ", ",
				entry.value.GoIdent, ".String(), ", fmtPackage.Ident("Sprintf"), "(format, args...))",
			)
			generated.P("}")
			generated.P()
		}
	}
}

func analyzeErrorFile(file *protogen.File) (errorFileModel, error) {
	var model errorFileModel
	for _, enum := range file.Enums {
		defaultCode, hasDefault, err := optionCode(enum.Desc.Options(), errorsv1.E_DefaultCode)
		if err != nil {
			return errorFileModel{}, fmt.Errorf("%s default error code: %w", enum.Desc.FullName(), err)
		}

		enumModel := errorEnumModel{
			enum:   enum,
			values: enum.Values,
		}
		recognized := hasDefault
		for _, value := range enum.Values {
			code := defaultCode
			override, hasOverride, optionErr := optionCode(value.Desc.Options(), errorsv1.E_Code)
			if optionErr != nil {
				return errorFileModel{}, fmt.Errorf("%s error code: %w", value.Desc.FullName(), optionErr)
			}
			if hasOverride {
				code = override
				recognized = true
			}
			if !hasDefault && !hasOverride {
				continue
			}
			if code < 100 || code > 599 {
				return errorFileModel{}, fmt.Errorf(
					"%s error code %d is outside HTTP status range 100..599",
					value.Desc.FullName(),
					code,
				)
			}
			enumModel.entries = append(enumModel.entries, errorEntry{
				value:    value,
				code:     code,
				function: camelIdentifier(string(value.Desc.Name())),
				comment:  enumValueComment(value),
			})
		}
		if !recognized {
			continue
		}
		model.goEntryCount += len(enumModel.entries)
		model.enums = append(model.enums, enumModel)
	}
	return model, nil
}

func optionCode(message proto.Message, extension protoreflect.ExtensionType) (int32, bool, error) {
	if !proto.HasExtension(message, extension) {
		return 0, false, nil
	}
	value := proto.GetExtension(message, extension)
	code, ok := value.(int32)
	if !ok {
		return 0, false, fmt.Errorf("unexpected option value type %T", value)
	}
	return code, true, nil
}

func camelIdentifier(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '_' })
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		part = strings.ToLower(part)
		first, size := utf8.DecodeRuneInString(part)
		result.WriteRune(unicode.ToUpper(first))
		result.WriteString(part[size:])
	}
	return result.String()
}

func enumValueComment(value *protogen.EnumValue) string {
	comment := strings.TrimSpace(value.Comments.Leading.String())
	if comment == "" {
		comment = strings.TrimSpace(value.Comments.Trailing.String())
	}
	return comment
}
