package main

import "google.golang.org/protobuf/compiler/protogen"

const typeScriptGeneratedSuffix = ".errors.ts"

func generateTypeScriptFile(plugin *protogen.Plugin, file *protogen.File, model errorFileModel) {
	if len(model.enums) == 0 {
		return
	}

	generated := plugin.NewGeneratedFile(
		file.GeneratedFilenamePrefix+typeScriptGeneratedSuffix,
		file.GoImportPath,
	)
	generated.P("// Code generated by protoc-gen-go-errors. DO NOT EDIT.")
	generated.P()
	generated.P("import type {")
	for _, enum := range model.enums {
		name := string(enum.enum.Desc.Name())
		generated.P("  ", name, " as ", name, "Type,")
	}
	generated.P("} from './index.js';")

	for _, enum := range model.enums {
		name := string(enum.enum.Desc.Name())
		generated.P()
		generated.P("export type ", name, " = ", name, "Type;")
		generated.P()
		generated.P("export const ", name, " = {")
		for _, value := range enum.values {
			valueName := string(value.Desc.Name())
			generated.P("  ", valueName, ": '", valueName, "',")
		}
		generated.P("} as const satisfies {")
		generated.P("  readonly [K in ", name, "Type]: K;")
		generated.P("};")
		generated.P()
		generated.P("export function is", name, "(value: unknown): value is ", name, " {")
		generated.P("  return (")
		generated.P("    typeof value === 'string' &&")
		generated.P("    Object.prototype.hasOwnProperty.call(", name, ", value)")
		generated.P("  );")
		generated.P("}")
	}
}
