// Command protoc-gen-servora-audit translates servora audit proto annotations
// into a Go file (`audit_rules.gen.go`) consumed by the audit middleware at runtime.
//
// Merge semantics (matches authn / authz):
//   - method-level rule with mode != AUDIT_MODE_UNSPECIFIED replaces the
//     service-level default in its entirety,
//   - method-level rule absent (or mode == AUDIT_MODE_UNSPECIFIED) inherits
//     the service-level default,
//   - only methods whose merged mode is AUDIT_MODE_ENABLED reach the generated
//     output; AUDIT_MODE_DISABLED and methods with no resolved rule are skipped.
//
// Cross-file template scanning: rules are gathered from ALL input files
// (including non-generated dependencies). Templates are keyed by proto
// fully-qualified service name so same-named services in different packages do
// not share rules. Generated output groups by output directory so each
// directory yields one audit_rules.gen.go covering the services declared in it.
package main

import (
	"fmt"
	"path"

	auditv1 "github.com/Servora-Kit/servora/api/gen/go/servora/audit/v1"
	"github.com/Servora-Kit/servora/cmd/internal/ruleplan"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		return generate(gen)
	})
}

// generate is the testable entry point.
func generate(gen *protogen.Plugin) error {
	groups, err := ruleplan.Build(gen, ruleplan.Config[*auditv1.AuditRule]{
		MethodExtension:  auditv1.E_Rule,
		ServiceExtension: auditv1.E_ServiceDefault,
		AcceptMerged: func(_ ruleplan.MethodContext, rule *auditv1.AuditRule) (bool, error) {
			return rule.GetMode() == auditv1.AuditMode_AUDIT_MODE_ENABLED, nil
		},
	})
	if err != nil {
		return err
	}
	for _, group := range groups {
		file := group.TargetFile
		generated := gen.NewGeneratedFile(
			path.Join(group.Directory, "audit_rules.gen.go"),
			file.GoImportPath,
		)
		generateFile(generated, file.GoPackageName, group.Entries)
	}
	return nil
}

func generateFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, rules []ruleplan.Entry[*auditv1.AuditRule]) {
	auditv1Pkg := protogen.GoImportPath("github.com/Servora-Kit/servora/api/gen/go/servora/audit/v1")

	g.P("// Code generated by protoc-gen-servora-audit. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	auditRule := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AuditRule", GoImportPath: auditv1Pkg})
	auditModeEnabled := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AuditMode_AUDIT_MODE_ENABLED", GoImportPath: auditv1Pkg})

	g.P("// AuditRules returns the audit rules for this package.")
	g.P("// Merge these with other packages' rules using audit.Middleware WithRulesFuncs.")
	g.P("func AuditRules() map[string]*", auditRule, " {")
	g.P("	return map[string]*", auditRule, "{")
	for _, entry := range rules {
		g.P(fmt.Sprintf("\t\t%q: {Mode: ", entry.Operation), auditModeEnabled, "},")
	}
	g.P("	}")
	g.P("}")
}
