// Code generated by protoc-gen-redact. DO NOT EDIT.
// source: cmd/protoc-gen-redact/testdata/redact_test.proto

package testdata

import (
	redactv3 "github.com/Servora-Kit/servora/api/gen/go/servora/redact/v3"
	proto "google.golang.org/protobuf/proto"
)

var _ redactv3.FieldRules

// Redact returns a redacted representation without mutating x.
func (x *LoginRequest) Redact() string {
	if x == nil {
		return ""
	}
	clone := proto.Clone(x).(*LoginRequest)
	clone.RedactFields()
	return clone.String()
}

// RedactFields applies annotated field replacements in place.
func (x *LoginRequest) RedactFields() {
	if x == nil {
		return
	}
	x.Password = ``
	x.CapToken = []byte(``)
}
