// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cmd/protoc-gen-redact/testdata/redact_test.proto

package testdata

import (
	_ "github.com/Servora-Kit/servora/api/gen/go/servora/redact/v3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CapToken      []byte                 `protobuf:"bytes,3,opt,name=cap_token,json=capToken,proto3" json:"cap_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_cmd_protoc_gen_redact_testdata_redact_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_redact_testdata_redact_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCapToken() []byte {
	if x != nil {
		return x.CapToken
	}
	return nil
}

var File_cmd_protoc_gen_redact_testdata_redact_test_proto protoreflect.FileDescriptor

const file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDesc = "" +
	"\n" +
	"0cmd/protoc-gen-redact/testdata/redact_test.proto\x12\rredacttest.v1\x1a\x1eservora/redact/v3/redact.proto\"n\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\"\n" +
	"\bpassword\x18\x02 \x01(\tB\x06ڶ\x1a\x02z\x00R\bpassword\x12$\n" +
	"\tcap_token\x18\x03 \x01(\fB\aڶ\x1a\x03\x82\x01\x00R\bcapTokenBHZFgithub.com/Servora-Kit/servora/cmd/protoc-gen-redact/testdata;testdatab\x06proto3"

var (
	file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescData []byte
)

func file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDesc), len(file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDesc)))
	})
	return file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDescData
}

var file_cmd_protoc_gen_redact_testdata_redact_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_protoc_gen_redact_testdata_redact_test_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: redacttest.v1.LoginRequest
}
var file_cmd_protoc_gen_redact_testdata_redact_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_redact_testdata_redact_test_proto_init() }
func file_cmd_protoc_gen_redact_testdata_redact_test_proto_init() {
	if File_cmd_protoc_gen_redact_testdata_redact_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDesc), len(file_cmd_protoc_gen_redact_testdata_redact_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_redact_testdata_redact_test_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_redact_testdata_redact_test_proto_depIdxs,
		MessageInfos:      file_cmd_protoc_gen_redact_testdata_redact_test_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_redact_testdata_redact_test_proto = out.File
	file_cmd_protoc_gen_redact_testdata_redact_test_proto_goTypes = nil
	file_cmd_protoc_gen_redact_testdata_redact_test_proto_depIdxs = nil
}
