package main

import (
	"os"
	"path/filepath"
	"text/template"

	pgs "github.com/lyft/protoc-gen-star/v2"
	pgsGo "github.com/lyft/protoc-gen-star/v2/lang/go"
)

// Redactor returns the implementation of the protoc-gen-redact plugin
// to generate redaction file
func Redactor() pgs.Module { return &Module{ModuleBase: &pgs.ModuleBase{}} }

// Module implements the pgs.Module interface for protoc-gen-redact plugin
type Module struct {
	*pgs.ModuleBase
	ctx  pgsGo.Context
	tmpl *template.Template
}

// Name returns the name of this protoc-gen-star module
func (*Module) Name() string { return "redactor" }

// InitContext satisfies the pgs.Module interface and helps build the module
func (m *Module) InitContext(c pgs.BuildContext) {
	// Add panic recovery for initialization
	defer func() {
		if r := recover(); r != nil {
			m.Failf("Panic during module initialization: %v", r)
		}
	}()

	m.ModuleBase.InitContext(c)
	m.ctx = pgsGo.InitContext(c.Parameters())

	// Validate context
	if m.ctx == nil {
		m.Fail("Failed to initialize Go context")
		return
	}

	// Check for custom template file parameter
	templateFile := c.Parameters().Str("template_file")

	tpl := template.New("redact").Funcs(map[string]interface{}{
		"package": m.ctx.PackageName,
		"name":    m.ctx.Name,
	})

	var parsedTpl *template.Template
	var err error

	if templateFile != "" {
		// Load template from external file
		m.Debug("Loading template from file: " + templateFile)
		parsedTpl, err = m.loadTemplateFromFile(tpl, templateFile)
		if err != nil {
			m.Failf("Failed to load template from file %s: %v", templateFile, err)
			return
		}
		m.Debug("Successfully loaded external template")
	} else {
		// Use embedded template
		m.Debug("Using embedded template")
		parsedTpl, err = tpl.Parse(redactTpl)
		if err != nil {
			m.Failf("Failed to parse embedded template: %v", err)
			return
		}
	}

	m.tmpl = parsedTpl
	m.Debug("Module initialized successfully")
}

// Execute satisfies the pgs.Module interface & generates the redactor file
// for the targeted files
func (m *Module) Execute(targets map[string]pgs.File, _ map[string]pgs.Package) []pgs.Artifact {
	// process all the target files
	for _, file := range targets {
		m.Process(file)
	}
	return m.Artifacts()
}

// loadTemplateFromFile loads a template from an external file
func (m *Module) loadTemplateFromFile(tpl *template.Template, templatePath string) (*template.Template, error) {
	// Validate the file path
	if templatePath == "" {
		return nil, ErrorContext{
			Location: "template_file parameter",
			Reason:   "template file path is empty",
		}
	}

	// Resolve absolute path
	absPath, err := filepath.Abs(templatePath)
	if err != nil {
		return nil, ErrorContext{
			Location: "template_file: " + templatePath,
			Reason:   "failed to resolve absolute path: " + err.Error(),
		}
	}

	// Check if file exists
	fileInfo, err := os.Stat(absPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrorContext{
				Location: "template_file: " + absPath,
				Reason:   "file does not exist",
			}
		}
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "failed to stat file: " + err.Error(),
		}
	}

	// Check if it's a regular file
	if !fileInfo.Mode().IsRegular() {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "path is not a regular file",
		}
	}

	// Check file size (limit to 10MB for safety)
	const maxTemplateSize = 10 * 1024 * 1024 // 10MB
	if fileInfo.Size() > maxTemplateSize {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "template file is too large (max 10MB)",
		}
	}

	// Read the template file
	templateContent, err := os.ReadFile(absPath)
	if err != nil {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "failed to read file: " + err.Error(),
		}
	}

	// Parse the template
	parsedTpl, err := tpl.Parse(string(templateContent))
	if err != nil {
		return nil, ErrorContext{
			Location: "template_file: " + absPath,
			Reason:   "failed to parse template: " + err.Error(),
		}
	}

	m.Debug("Template loaded successfully from: " + absPath)
	return parsedTpl, nil
}

const redactTpl = `{{ $data := . }}
// Code generated by protoc-gen-redact. DO NOT EDIT.
// source: {{ $data.Source }}

package {{ $data.Package }}

import (
	{{- range $alias, $path := $data.Imports }}
	{{ $alias }} "{{ $path }}"
	{{- end }}
)

{{ range $name := $data.References }}
var _ {{ $name }}
{{- end }}

{{ range $msg := $data.Messages }}
// Redact returns a redacted representation without mutating x.
func (x *{{ $msg.Name }}) Redact() string {
	if x == nil {
		return ""
	}
	clone := proto.Clone(x).(*{{ $msg.Name }})
	clone.RedactFields()
	return clone.String()
}

// RedactFields applies annotated field replacements in place.
func (x *{{ $msg.Name }}) RedactFields() {
	if x == nil {
		return
	}
	{{- range $field := $msg.Fields }}
	{{- if $field.Redact }}
		{{- if $field.Iterate }}
		for k := range x.{{ $field.Name }} {
			x.{{ $field.Name }}[k] = {{ $field.RedactionValue }}
		}
		{{- else if $field.IsMessage }}
			{{- if $field.NestedEmbedCall }}
		if redacter, ok := any(x.{{ $field.Name }}).(interface{ RedactFields() }); ok {
			redacter.RedactFields()
		}
			{{- else if not $field.EmbedSkip }}
		x.{{ $field.Name }} = {{ $field.RedactionValue }}
			{{- end }}
		{{- else if $field.IsOptional }}
		{{- if eq $field.FieldGoType "string" }}
		value := {{ $field.RedactionValue }}
		x.{{ $field.Name }} = &value
		{{- else }}
		value := {{ $field.FieldGoType }}({{ $field.RedactionValue }})
		x.{{ $field.Name }} = &value
		{{- end }}
		{{- else }}
		x.{{ $field.Name }} = {{ $field.RedactionValue }}
		{{- end }}
	{{- end }}
	{{- end }}
	{{- range $oneof := $msg.Oneofs }}
	{{- if $oneof.HasRedactableFields }}
	switch v := x.{{ $oneof.Name }}.(type) {
	{{- range $field := $oneof.Fields }}
	{{- if $field.Redact }}
	case *{{ $field.WrapperTypeName }}:
		{{- if $field.IsMessage }}
			{{- if $field.NestedEmbedCall }}
		if redacter, ok := any(v.{{ $field.Name }}).(interface{ RedactFields() }); ok {
			redacter.RedactFields()
		}
			{{- else if not $field.EmbedSkip }}
		v.{{ $field.Name }} = {{ $field.RedactionValue }}
			{{- end }}
		{{- else }}
		v.{{ $field.Name }} = {{ $field.RedactionValue }}
		{{- end }}
	{{- end }}
	{{- end }}
	}
	{{- end }}
	{{- end }}
}
{{- end }}
`
